services: #docker run --name fastapi-container -p 5002:5002 -d -v $(pwd):/app fastapi-image
  app:
    build: ..
    container_name: python-server
    # environemnt path is relative to build path above
    environment:
      - FLASK_APP=src/hello
    # command: uvicorn src.main:app --host 0.0.0.0 --port 5002 --reload
    # flask framework requires "FLASK_APP" in environment setting
    command: flask run  --host 0.0.0.0 --port 5002
    ports:
      - 5002:5002
      - 5678:5678 #debugpy
    volumes:
      - ..:/workspace
    depends_on:
      - redis

  redis:
    image: redis:alpine
